### ISSUE TITLE
完了。作者弃坑了

### ISSUE THREAD

**Issue by helloworld10010** [WX-JIN/JGallery#9]

**Comment by helloworld10010** [comment]
5个小时前更新？            兄得。我直接compile 一直报 glide版本未指定。然后我吧jgallery源码导入后依赖，更改okhttp版本，解决。 现在一运行报`Process: com.aorong.jarvis.play, PID: 4176
    android.view.InflateException: Binary XML file line #11: Error inflating class com.soubw.view.JVideoView
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at com.soubw.jgallery.JGalleryRecycleAdapter.loadLayout(JGalleryRecycleAdapter.java:195)
        at com.soubw.jgallery.JGalleryPagerAdapter.onCreateViewHolder(JGalleryPagerAdapter.java:46)
        at com.soubw.jgallery.JGalleryPagerAdapter.onCreateViewHolder(JGalleryPagerAdapter.java:24)
        at com.soubw.jgallery.JGalleryRecycleAdapter.getView(JGalleryRecycleAdapter.java:56)
        at com.soubw.salvage.RecyclingPagerAdapter.instantiateItem(RecyclingPagerAdapter.java:39)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16497)
        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:401)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:544)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
    	at java.lang.reflect.Method.invokeNativ`

资源文件问题？一直在看。看傻了

**Comment by helloworld10010** [comment]
坐等回复

**Comment by helloworld10010** [comment]
加了一个`values-w820dp`文件夹解决以上报错了，现在`LargerImageView`类报空指针。`mDecoder` 由于`setInputStream`函数没有调用 造成为`null`，所以空指针，那么这么函数该在哪调。。

**Comment by WX-JIN** [comment]
> 加了一个`values-w820dp`文件夹解决以上报错了，现在`LargerImageView`类报空指针。`mDecoder` 由于`setInputStream`函数没有调用 造成为`null`，所以空指针，那么这么函数该在哪调。。

哥们，实在抱歉，之前的重构中，把代码提交了，现在事情比较多，就没有继续搞了，之后提交，你可以先用之前第一版本，不会出错的版本1.0.2

**Comment by helloworld10010** [comment]
> > 加了一个`values-w820dp`文件夹解决以上报错了，现在`LargerImageView`类报空指针。`mDecoder` 由于`setInputStream`函数没有调用 造成为`null`，所以空指针，那么这么函数该在哪调。。
> 
> 哥们，实在抱歉，之前的重构中，把代码提交了，现在事情比较多，就没有继续搞了，之后提交，你可以先用之前第一版本，不会出错的版本1.0.2

关键是gradle引用的1.0.2不能用。不然我这么麻烦干嘛--。我在`app`的`build.gradle`里添加的`compile 'com.soubw:jgallery:1.0.2'`，应该没问题吧？报这个`Failed to resolve: glide-parent:library:unspecified
Open File
Show in Project Structure dialog`  拜托，尽快修复一下1.0.2也好

**Comment by helloworld10010** [comment]
傻屌了。代码在这，直接reset不完了。哈哈哈

**Comment by helloworld10010** [comment]
着急用的可以先参考这个。 在作者源码基础上改了改。他‘重构’完成时删除。https://github.com/helloworld10010/jGalleryTemp
